#!/bin/zsh

local PLUGIN_FILE="doc/zshnavigationtools.plugin.zsh"

[ -d doc ] || cd ..

rm -vf "$PLUGIN_FILE"
echo "# The preamble comments apply when using ZNT as autoload functions" >>"$PLUGIN_FILE"
echo "# https://github.com/psprint/zsh-navigation-tools" >>"$PLUGIN_FILE"
echo "# License is GPLv3" >>"$PLUGIN_FILE"
echo -n "# " >>"$PLUGIN_FILE"
git show-ref master | head -1 >>"$PLUGIN_FILE"
echo >>"$PLUGIN_FILE"

for i in n-*(on); do
    echo "$i() {" >>"$PLUGIN_FILE"
    cat "$i" >>"$PLUGIN_FILE"
    echo "}" >>"$PLUGIN_FILE"
    echo "alias n${i#n-}=$i" >>"$PLUGIN_FILE"
    echo >>"$PLUGIN_FILE"
done

# Append znt-* files
for i in znt-*(on); do
    echo "$i() {" >>"$PLUGIN_FILE"
    cat "$i" >>"$PLUGIN_FILE"
    echo "}" >>"$PLUGIN_FILE"
    echo >>"$PLUGIN_FILE"
done
